### ISSUE TITLE
Crash in load_madminer_settings in files with custom observables

### ISSUE THREAD

**Issue by rbarrue** [madminer-tool/madminer#501]
When running _load_madminer_settings_ (https://github.com/madminer-tool/madminer/blob/master/madminer/utils/interfaces/hdf5.py#L29) on a .h5 file created with custom observables added via the _add_observable_from_function_ (https://github.com/madminer-tool/madminer/blob/master/madminer/lhe/lhe_reader.py#L345), I'm getting an error "SyntaxError: unexpected EOF while parsing" when creating the Observable object in https://github.com/madminer-tool/madminer/blob/master/madminer/models/readers.py#L50.

I've managed to track it down to the fact that, when saving the observable definitions into the file, if the observable is defined from a function, its definition is saved simply as an empty string (see https://github.com/madminer-tool/madminer/blob/master/madminer/utils/interfaces/hdf5.py#L1025).

If one of the devs has a quick fix for this, or can help me in finding a solution (unfortunately, I don't have much Python experience yet), I'd be very thankful.

**Comment by irinaespejo** [comment]
Hi @rbarrue 

Can you provide us with the snippet where you use _add_observable_from_function_? Maybe there are useful hints.
Also posting the entire error output can be helpful.

Thank you!

**Comment by alexander-held** [comment]
Hi @rbarrue, the changes seem to come from the refactor in #483. The comment above the code you linked (`# Filter out callable definitions when saving into HDF5 file`) seems to imply that this may be on purpose. In case @Sinclert might have time to take a look or remember more about this, he might know.

What was previously used to refer to the custom observable in the file? If you have a minimal reproducible example of this that you could share, this would be very useful to understand what the behavior should be. I'm happy to help with the Python side of things, but do not know this codebase very well unfortunately.

**Comment by Sinclert** [comment]
Hey @rbarrue 👋🏻 

As Alex pointed out, the [hdf5.py](https://github.com/madminer-tool/madminer/blob/master/madminer/utils/interfaces/hdf5.py) interface suffered a big refactor in PR https://github.com/madminer-tool/madminer/pull/483. Among the changes, multiple HDF5 keys were renamed, making pre `madminer` 0.9.0 setting files incompatible with `madminer` 0.9.0+ HDF5 parsing (as specified in the [0.9.0 release notes](https://github.com/madminer-tool/madminer/releases/tag/v0.9.0)). Make sure you have generated your settings with the latest `madminer` version  (`0.9.2`).

Considering that has been done, I can see that the referenced lines:
https://github.com/madminer-tool/madminer/blob/6556f164725baab6b79e5ffa2a64913a0ac50f7a/madminer/utils/interfaces/hdf5.py#L1024-L1026

were already present before the refactor:
https://github.com/madminer-tool/madminer/blob/58d63198e05a464d1336d8b60149e15274b889bc/madminer/utils/interfaces/madminer_hdf5.py#L524-L529

So... if you are having problems with an observable definition that worked fine pre v0.9.0, it may be a bug. As my colleagues have pointed out, **could you share your set up?**

- What version of `madminer` are you using to load the settings.
- What version of `madminer` was use to save the settings.
- What custom observables are you including in the _madminer settings_.

**Comment by rbarrue** [comment]
I was running this up until now on MadMiner v0.7.6 (it was working fine there), now I'm rerunning everything (even the setup file creation) on v0.9.2. The calculation of the observables is done properly, since the values are in the 'observations' column in the analysed .h5 files. To mention that this problem appears already in the processing stage if I do _lhe.save(shuffle=True)_.

I'm uploading a minimal working example [here](https://cernbox.cern.ch/index.php/s/p77Jc2jFtvpKGje) with two 50k event .lhe files (sorry for the size, but these were the smallest ones I had), which are analysed and can then be combined at the end. I've already produced a set of analysed .h5 files which you can inspect, and if you want to see the error just run the code as-is, with the process_events functions commented. If you want to reanalyse the files, just uncomment the lines.

@irinaespejo the error is:
File "/cvmfs/sw.el7/python/3.7.2/lib/python3.7/site-packages/madminer/sampling/combine.py", line 127, in combine_and_shuffle
    ) = load_madminer_settings(filename, include_nuisance_benchmarks=False)
  File "/cvmfs/sw.el7/python/3.7.2/lib/python3.7/site-packages/madminer/utils/interfaces/hdf5.py", line 115, in load_madminer_settings
    observables[o_name] = Observable(o_name, o_def)
  File "<string>", line 6, in __init__
  File "/cvmfs/sw.el7/python/3.7.2/lib/python3.7/site-packages/madminer/models/readers.py", line 50, in __post_init__
    eval(self.val_expression)
  File "<string>", line 0
    
    ^

**Comment by Sinclert** [comment]
@rbarrue I think I found the "bug":

### Context
After the migration of _column-oriented_ models to _object-oriented_ models described by issue https://github.com/madminer-tool/madminer/issues/482 (to which PRs https://github.com/madminer-tool/madminer/pull/483, https://github.com/madminer-tool/madminer/pull/484 and https://github.com/madminer-tool/madminer/pull/485 belong) was completed, both `LHEReader` and `DelphesReader` classes are safety-checking the definition of its internal models, to ensure that they do not have `SyntaxErrors` (`NameErrors` are actually fine at this stage).

You can see that all reader-based data classes do so:
- The `Cut` model in [these lines](https://github.com/madminer-tool/madminer/blob/6556f164725baab6b79e5ffa2a64913a0ac50f7a/madminer/models/readers.py#L17-L18).
- The `Efficiency` model in [these lines](https://github.com/madminer-tool/madminer/blob/6556f164725baab6b79e5ffa2a64913a0ac50f7a/madminer/models/readers.py#L31-L32).
- **The `Observable` model in [these lines](https://github.com/madminer-tool/madminer/blob/6556f164725baab6b79e5ffa2a64913a0ac50f7a/madminer/models/readers.py#L46-L50)**.

This _standardisation of safety-checks within models creation_ has caused that, classes that did not included them in the first place (like the `LHEReader` class), are now doing so (and for good!). You can check how reader classes differ in this approach before Madminer `v0.9.0`:
- **The `LHEReader` class [did not safety check the definitions](https://github.com/madminer-tool/madminer/blob/9de9569bb53881e205942b745ca04dfc9774137c/madminer/lhe/lhe_reader.py#L321-L328)**.
- The `DelphesReader` class [did safety check the definitions](https://github.com/madminer-tool/madminer/blob/9de9569bb53881e205942b745ca04dfc9774137c/madminer/delphes/delphes_reader.py#L384).

---

### The bug
Now that both `LHEReader` and `DelphesReader` classes use safety-checks under-the-hood, an **already existing bug** within the Madminer codebase has resurfaced:

> Setting the empty string value (`""`) as _default_ for callable `Observable` definitions (in [this line](https://github.com/madminer-tool/madminer/blob/6556f164725baab6b79e5ffa2a64913a0ac50f7a/madminer/utils/interfaces/hdf5.py#L1025)), is incompatible with safety-checking `Observable` models at creation ([these lines](https://github.com/madminer-tool/madminer/blob/6556f164725baab6b79e5ffa2a64913a0ac50f7a/madminer/models/readers.py#L46-L50)).

---

### Solution
The solution would involve using a _dummy_ parseable Python symbol (one that when doing `eval(<symbol>)` does not raise any errors), so that when safety-checking the callables, no exception is raised. I think the best candidate is `None` as a string (therefore `"None"`).

Knowing the this using the empty string is a problem when safety-checking using Python's `eval()`, this fix can also be included in other serialization functions, such as:

**Comment by rbarrue** [comment]
(sorry, closed this on accident) so, the solution would simply be to replace

**Comment by Sinclert** [comment]
Yes. That should be it.

Could you run your analysis either (A) modifying your local copy of `madminer`, or (B) installing a customised fork of `madminer`, to verify whether or not my proposal fixes your crash?

If the answer is positive, I am open to review a PR including those changes **in addition to the necessary tests so that this _loading - saving setting inconsistency_ do not happen again**. Finally, I could release version `0.9.3`.

**Comment by Sinclert** [comment]
@rbarrue can you confirm whether or not [the described bug-fix](https://github.com/madminer-tool/madminer/issues/501#issuecomment-1050810452) is enough to solve your problem?

**Comment by rbarrue** [comment]
> @rbarrue can you confirm whether or not [the described bug-fix](https://github.com/madminer-tool/madminer/issues/501#issuecomment-1050810452) is enough to solve your problem?

Hi Sinclert, sorry for only coming back to this today. I'll test the proposed implementation tomorrow and give you feedback.

**Comment by rbarrue** [comment]
Hi @Sinclert, I tested the proposed changes and everything seems to work as expected. In your comment, you mentioned "in addition to the necessary tests so that this loading - saving setting inconsistency do not happen again", are you talking about adding some tests to the [tests](https://github.com/madminer-tool/madminer/tree/master/tests) folder ?

**Comment by Sinclert** [comment]
Hi @rbarrue ,

Yes, exactly. Right now the [tests](https://github.com/madminer-tool/madminer/tree/master/tests) folder is pretty empty, but I (we?) would like that to change.

What a better opportunity to start? 🙂 

I would envision creating a `tests/utils/interfaces/test_hdf5.py` file (mimicking the folder structure under [`madminer`](https://github.com/madminer-tool/madminer/tree/master/madminer)), with a small set of test functions covering the saving-loading of _madminer settings_, in order to check that the model definitions being saved (whether it is `Observable`,`NuisanceParameter` or  `Systematics` ) are valid upon `eval(self.val_definition)` (such as the one done [within the models](https://github.com/madminer-tool/madminer/blob/6556f164725baab6b79e5ffa2a64913a0ac50f7a/madminer/models/readers.py)).

**Comment by Sinclert** [comment]
The fix was merged, and [version `0.9.3` published](https://pypi.org/project/madminer/0.9.3/) ✅ 

Closing issue.

**Comment by rbarrue** [comment]
Thank you very much @Sinclert !
