### ISSUE TITLE
Error calculating Fisher information in MadMiner(v0.9.3)

### ISSUE THREAD

**Issue by roshan-mammen-abraham** [madminer-tool/madminer#517]
Hello,

I wanted to raise the following issue in v0.9.3. I was going through the tutorial_particle_physics example provided with MadMiner (v0.9.3). There were some errors in some of the notebooks (screenshots attached) that prevented a Fisher information calculation from histograms from going through. (Using the SALLY network works though.)

In 2a_parton_level_analysis, while loading the "setup.h5" file it throws some errors (attached screenshots). I am not explicitly setting any nuisance parameters for systematics.

In 4b_fisher_information, while loading the "lhe_data_shuffled.h5" it says "Did not find nuisance morphing setup". It then fails at the fisher.histo_information function.

My colleague could not replicate the issue when using v0.7.4.  I was wondering if you could be of any assistance in this matter.

Thank you very much
<img width="1009" alt="2a_parton_level_analysis" src="https://user-images.githubusercontent.com/87339279/195421339-c6024764-616b-4056-8358-f2f8d3e2c2bf.png">
<img width="1028" alt="4b_fisher_information_loading" src="https://user-images.githubusercontent.com/87339279/195421349-368a1510-d7fb-4db9-abc7-625ed18233d3.png">
<img width="519" alt="4b_fisher_information" src="https://user-images.githubusercontent.com/87339279/195421346-ae659958-2364-489c-ad0c-3cd6d50b48aa.png">

**Comment by Sinclert** [comment]
👋🏻 Hi Roshan.

Thanks for reporting all these problems. I will address them in order:

---

> In _2A_parton_level_analysis_, while loading the "setup.h5" file it throws some errors (attached screenshots). I am not explicitly setting any nuisance parameters for systematics.

These error messages are "expected". When MadMiner jumped from version `0.8.3` to `0.9.0` a huge refactor of the HDF5 interface was made (see [this PR](https://github.com/madminer-tool/madminer/pull/483) for complete context), and these messages were introduced. This was done in order to add visibility when the `MadMiner.load` method call the `load_madminer_settings` function ([reference](https://github.com/madminer-tool/madminer/blob/v0.9.0/madminer/core/madminer.py#L493-L509)) to load settings from a HDF5 file, as it eagerly tries to load **every possible setting**.

I see how labelling these messages as _ERROR_ is confusing. They should be _INFO_ messages.

---

> In 4b_fisher_information, while loading the "lhe_data_shuffled.h5" it says "Did not find nuisance morphing setup".

That is expected, and as far as I know, that part of the code preserves the same behaviour has < `0.9.0` versions.

Could you elaborate on why this behaviour surprised you?

---

> It then fails at the fisher.histo_information function.

This is the real bug 🐛 

I can see that on MadMiner `v0.8.3` the `DataAnalyzer` class was hardcoding `False` for its `include_nuisance_parameters` attribute when there were no _nuisance parameters_ ([reference](https://github.com/madminer-tool/madminer/blob/v0.8.3/madminer/analysis/dataanalyzer.py#L71-L77)). Even if this approach is the one @rbarrue mentioned on Gitter as option A to fix the problem, it does not feel natural, as the class will be overriding the value the user provided, which is not good for traceability purposes.

I will think about a solution to this problem that does not involve overriding the user input.

**Comment by rbarrue** [comment]
I believe we could start with a controlled crash with a message informing that the settings should be consistent, e.g. "you asked for systematics, but did not define any in your setup file, confirm your settings and rerun. Exiting..."

@Sinclert is this how it's done in the SW dev. world ?

**Comment by roshan-mammen-abraham** [comment]
Hello,

Thank you for the resonse. Regarding _In 4b_fisher_information, while loading the "lhe_data_shuffled.h5" it says "Did not find nuisance morphing setup"_  I mentioned it only as I had thought it could be a cause for the latter issue. Nothing more.

Thank you.

**Comment by rbarrue** [comment]
Looks great, thanks for the ping @Sinclert !

**Comment by Sinclert** [comment]
Just released version `0.9.5` with the fix.

I will close this issue for now. Feel free to open it if the problem persist.
