### ISSUE TITLE
AttributeError: 'AsymptoticLimits' object has no attribute '_calculate_partition_bound'

### ISSUE THREAD

**Issue by samiur06** [madminer-tool/madminer#531]
Hi there,

I am using MadMiner v0.9.5 and trying to reproduce the results of `4a_limits.ipynb` from the example `tutorial_particle_physics`. I am getting this following attribute error, when I call `expected_limits` function: 

![Screen Shot 2023-01-19 at 4 03 33 PM](https://user-images.githubusercontent.com/94074635/213573570-6fd16f83-ed9c-4d99-a0a8-9e5f505ae07f.png)

Evidently, the compiler is complaining about undefined `_calculate_partition_bounds` function in the file  `madminer/limits/asymptotic_limits.py`. 

`_calculate_partition_bounds` was defined in the `analysis` package and that package was imported in `asymptotic_limits.py` source code. So there shouldn't be an error. 

Note that I don't have any issue running the programs of step 3 of the same tutorial.  Some help on this matter would be appreciated!

**Comment by Sinclert** [comment]
Hey @samiur06 , thanks for the report.

This error is due to a _very dumb_ typo, eventually fixed by [this PR](https://github.com/madminer-tool/madminer/commit/92440bfed3e30d1539464a8127898c060ddd3694). We just haven't released a new version of the package yet. Will do that so folks can run the examples without trouble.

**Comment by samiur06** [comment]
The issue is no longer there. Thank you very much for the quick response, much appreciated!
